### PR TITLE
Zarr for saving

### PR DESCRIPTION
**Pull request by AaronDavidSchneider**
- replace write to nc by write to zarr
- option to read all files

Advantage of zarr over nc is that zarr splits to multiple files and is therefore better to handle in terms of IO in case of large datasets (e.g. many many timesteps), zarr will also integrate with dask.

### CODE REVIEW

**Comment by AaronDavidSchneider** [comment]
we could alternatively have `.nc` and `.zarr` and rename `save` and `load` to `save_nc` and `load_nc` and `save_zarr` and `load_zarr`.

What do you think @robinbaeyens ?

**Review by robinbaeyens — CHANGES_REQUESTED** [review]
Nice find on the .zarr format! I hadn't heard of it before. 
Although it seems very useful, I think replacing .nc by .zarr is not the right way to go. NetCDF is very widely used from what I've heard, e.g. also in the Exeter UM group and in the Earth-climate community. So I would go for the 2 methods (or one method with a given argument 'nc' or 'zarr'), so the user can choose.

**Comment by AaronDavidSchneider** [comment]
> So I would go for the 2 methods (or one method with a given argument 'nc' or 'zarr'), so the user can choose.

Yes I agree! I will adapt the PR! Thanks for your feedback!

**Comment by AaronDavidSchneider** [comment]
What do you think about the update @robinbaeyens ?

**Review by robinbaeyens — APPROVED** [review]
Nice, looks good like this!

**Pull request merged**
