### PR TITLE
add testing framework

### PR DESCRIPTION
**Pull request by AaronDavidSchneider**
This PR brings a testing framework for unittests, inclunding CI. More tests to come. These tests work as expected locally on my machine. Lets see what the CI does.

### CODE REVIEW

**Comment by AaronDavidSchneider** [comment]
Explanation on testing framework:
1. Tests are automatically performed for each pull request and for each push to a branch.
2. Tests can be performed locally using `py.test GCMtools` (when you are in the folder that contains GCMtools)

The setup of the tests is defined in `tests/test_gcmtools_common.py` where the handling of the test datasets is done. This can be easily extended to more experiments, for example, when we support more gcms.

The actual tests are then performed in the individual `test_*` files. Currently there is only a very limited test in `test_gcmt.py`. We can of course always add on top of that.

Credits: The people from `xmitgcm`. This framework is basically just adapting theirs.

**Comment by AaronDavidSchneider** [comment]
> The changes looks good and I'm happy to see that testing seems to work. I agree with the codecov that we should aim to have a coverage of 95%, especially since this will be the basis of (maybe) a much larger framework. Let me know if you need help setting up the tests!

Yes that would be the goal. However, some stuff is difficult to test. One example being the plotting routines. It needs to be decided if those can be excluded from testing coverage.

> Furthermore, it might be useful to also think about style guides like pylint and pycodestyle. I find them often helpful even if they are not fully enforced. I know you can set them up similar to codecov but never did it myself before.

I agree! Its easy to add them. We just need to find a repo, where someone did this already :D

**Comment by Kiefersv** [comment]
> Yes that would be the goal. However, some stuff is difficult to test. One example being the plotting routines. It needs to be decided if those can be excluded from testing coverage.

Understandable and its definitely not our top priority. I still think it is worth putting in the effort but we can also add this at a later time when we have time.

> I agree! Its easy to add them. We just need to find a repo, where someone did this already :D

I know them from here: https://github.com/PynPoint/PynPoint

**Comment by AaronDavidSchneider** [comment]
> Understandable and its definitely not our top priority. I still think it is worth putting in the effort but we can also add this at a later time when we have time.

I totally agree! If you have good ideas for tests, please fell free to extend the tests! I will certainly add some more, when I have a good idea for a test.

Should we get this PR merged first, to have a testing base?

Should I exclude the plotting from cov?

**Comment by Kiefersv** [comment]
> Should we get this PR merged first, to have a testing base?

I think that's a good idea.

> Should I exclude the plotting from cov?

No, we should only exclude it if we don't want it to be tested, otherwise I'm gonna forget to add tests for it.

**Review by Kiefersv — APPROVED** [review]

**Pull request merged**
